# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
# auto: true
highlighter: pygments

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Andy24boyking
tagline: 点滴思考
author :
  name : Andy24boyking Hoo
  email : andy24boyking@gmail.com
  github : Andy24boyking
  twitter : Andy24boyking

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://andy24boyking.github.io

# markdown interpreter on github has changed from Maruku(defalult) to kraamdown 
markdown:      kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

# Define my own theme AH
AH:
  version : 0.1.0

  BASE_PATH : false
  ASSET_PATH : false

  naviga :
    /archives : Archives
    /about : About Me

  categories_path : /categories/
  tags_path : /tags/
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : disqus
    disqus :
      short_name : andy24boyking